#ifndef _CONFIG_H_
#define _CONFIG_H_

#define LD_CONFIG_WIDTH (1024/2)
#define LD_CONFIG_HEIGHT (768/2)
#define LD_CONFIG_ASPECT ((float)LD_CONFIG_WIDTH / (float)LD_CONFIG_HEIGHT)
#define LD_CONFIG_TITLE "LD41"
#define LD_CONFIG_SWAP_INTERVAL 1

#endif // !_CONFIG_H_
