#ifndef _CONFIG_H_
#define _CONFIG_H_

#define LD_CONFIG_SCALE (4)
#define LD_CONFIG_GAME_WIDTH (160)
#define LD_CONFIG_GAME_HEIGHT (144)
#define LD_CONFIG_WIDTH (LD_CONFIG_GAME_WIDTH * LD_CONFIG_SCALE)
#define LD_CONFIG_HEIGHT (LD_CONFIG_GAME_HEIGHT * LD_CONFIG_SCALE)
#define LD_CONFIG_ASPECT ((float)LD_CONFIG_WIDTH / (float)LD_CONFIG_HEIGHT)
#define LD_CONFIG_TITLE "ld"
#define LD_CONFIG_SWAP_INTERVAL 1

#endif // !_CONFIG_H_
